# Generated by Django 5.0.3 on 2024-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appglobal', '0002_alter_pinturas_litros'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
            ],
        ),
    ]
